version: "3.8"

services:
  mongo:
    image: mongo:8
    container_name: numer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: numer-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/Numer1
      - CORS_ORIGIN=http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: numer-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mongo-data: